Pulled changes from sebakami:i18n, missing menu.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -16,6 +16,14 @@ CFLAGS ?= -ggdb -fno-omit-frame-pointer -O2
 CFLAGS += -Wall -Werror -D_FORTIFY_SOURCE=2
 CFLAGS += -DVERSION=\"$(VERSION)\"
 CFLAGS += -Wno-error=deprecated-declarations
+CFLAGS += -DLOCALEDIR=\"$(LOCALEDIR)\"
+
+ifeq ($(PREFIX),)
+  PREFIX := /usr/local
+endif
+
+LOCALEDIR := $(DESTDIR)$(PREFIX)/share/locale
+include po/linguas
 
 PKG_CONFIG=pkg-config
 
@@ -49,10 +57,11 @@ ICON_FILE := $(DOMAIN_PREFIX).$(TARGET).png
 
 GLIB_COMPILE_RESOURCES := $(shell $(PKG_CONFIG) --variable=glib_compile_resources gio-2.0)
 
-all: $(TARGET) $(DESKTOP_FILE)
+all: $(TARGET) $(DESKTOP_FILE) i18n
 
 clean:
 	rm -f $(TARGET) $(DESKTOP_FILE) $(OBJS) $(XML_OBJ)
+	$(MAKE) -C po clean
 
 depclean:
 	rm -rf $(DEPDIR)
@@ -67,10 +76,6 @@ include $(wildcard $(DEPFILES))
 $(TARGET): $(OBJS)
 	cc -o $(TARGET) $(OBJS) ${LDFLAGS} -lm 
 
-ifeq ($(PREFIX),)
-  PREFIX := /usr/local
-endif
-
 BINDIR := $(DESTDIR)$(PREFIX)/bin
 ICONTOP := $(DESTDIR)$(PREFIX)/share/icons/hicolor
 ICONDIR := $(ICONTOP)/256x256/apps
@@ -79,6 +84,9 @@ DESKTOPDIR := $(DESTDIR)$(PREFIX)/share/applications
 $(DESKTOP_FILE): $(DESKTOP_FILE).template
 	sed 's_PREFIX_$(PREFIX)_' < $< > $@
 
+i18n:
+	$(MAKE) -C po update-mo || echo "failed to create translations, continuing without..."
+
 install: all
 	install -d $(BINDIR)
 	install -m 755 $(TARGET) $(BINDIR)
@@ -86,11 +94,19 @@ install: all
 	install -m 644 img/$(ICON_FILE) $(ICONDIR)
 	install -d $(DESKTOPDIR)
 	install -m 644 $(DESKTOP_FILE) $(DESKTOPDIR)
+	catalogs='$(LINGUAS)'; \
+	for lang in $$catalogs; do \
+		if [ -f po/$$lang.gmo ]; then \
+			install -v -d $(LOCALEDIR)/$$lang/LC_MESSAGES;  \
+			install -v -m 644 po/$$lang.gmo $(LOCALEDIR)/$$lang/LC_MESSAGES/alsa-scarlett-gui.mo; \
+		fi \
+	done
 
 uninstall:
 	rm -f $(BINDIR)/$(TARGET)
 	rm -f $(ICONDIR)/$(ICON_FILE)
 	rm -f $(DESKTOPDIR)/$(DESKTOP_FILE)
+	rm -f $(LOCALEDIR)/*/LC_MESSAGES/alsa-scarlett-gui.mo
 
 help:
 	@echo "alsa-scarlett-gui"
